language: node_js
node_js:
  - 6
  - 8
sudo: false
before_install: "npm install --global npm"
script: "npm run lint && npm run test-travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/06b722b9c1ca92dd4d75
